### PR TITLE
fix: add revenue conversion for optimizely

### LINKED ISSUE #10: should the `track` call modify `revenue` properties?
Optimizely expects all `revenue` amounts to be represented as in `Int` in cents. But other plugins to Segment don't have this requirement.

Should this plugin convert `revenue` values before calling the `Optimizely` plugin? Or, perhaps have an `init` parameter like `convertRevenueToCents` which would give the caller a way to configure this?

### PR DESCRIPTION
**Pull request by alanjcharles**
- Optimizely expects `revenue` to be represented in `cents` outlined [here](https://docs.developers.optimizely.com/experimentation-data/docs/event-api-troubleshooting#i-sent-events-with-revenue-values-through-the-api-but-the-revenue-is-not-calculated-correctly-on-the-results-page)
- adds check to convert revenue to a value optimizely expects
- resolves #10

### CODE REVIEW

**Review by bsneed — APPROVED** [review]

File: Sources/SegmentOptimizelyFullStack/OptimizelyFullStack.swift [hunk 1]
```diff
@@ -137,6 +137,21 @@ public class OptimizelyFullStack: DestinationPlugin {
...
         
+        var optimizelyEvent = event
+
+        if var properties = event.properties?.dictionaryValue {
+            if let revenue = properties["revenue"] {
+                if let actualRevenue = revenue as? Int {
+                    let optimizelyRevenue = actualRevenue * 100
+                    properties["revenue"] = optimizelyRevenue
+                } else if let actualRevenue = revenue as? Double {
+                    let optimizelyRevenue = Int(actualRevenue) * 100
```
Comment (skydivedan) [inline Sources/SegmentOptimizelyFullStack/OptimizelyFullStack.swift:148]: Thanks for getting this in, but this calculation is incorrect. Should be
`let optimizelyRevenue = Int(actualRevenue * 100)`

Comment (alanjcharles) [reply Sources/SegmentOptimizelyFullStack/OptimizelyFullStack.swift:148]: @skydivedan oops, that is embarrassing. Thanks for the catch. fixed in `1.2.1`
